# Generated by Django 6.0.5 on 2026-05-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock'),
    ]

    operations = [
    ]
