# Generated by Django 6.0.5 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20260513_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimientos',
            new_name='Movimiento',
        ),
    ]
